language: fortran
dist: xenial
install:
    - sudo apt-get -qq update
    - sudo apt-get install ninja python-pip python-dev build-essential
    - sudo pip install --upgrade pip
    - sudo pip install meson
script:
    - meson build
    - ninja -C build
    - ninja -C build test
