language: fortran
dist: xenial
install:
    - sudo add-apt-repository universe
    - sudo apt-get update
    - sudo apt-get install meson ninja
script:
    - meson build
    - ninja -C build
    - ninja -C build test
